openapi: 3.0.3
info:
  title: Smart House. API
  version: 0.0.1
paths:
  /devices:
    get:
      tags:
        - Device Control Service
      summary: Возвращает список всех устройств
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                      example: 1
                    device_type_id:
                      type: integer
                      example: 1
                    house_id:
                      type: number
                      example: 3
                    serial:
                      type: string
                      example: kj67:3818jh
                    status:
                      type: number
                      example: 1
        '404':
          description: Not found
        '500':
          description: Internal error

  /devices/{device_id}:
    get:
      tags:
        - Device Control Service
      summary: Возвращает подробную информацию об устройстве
      parameters:
        - name: device_id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                    example: 1
                  device_type_id:
                    type: integer
                    example: 1
                  house_id:
                    type: number
                    example: 3
                  serial:
                    type: string
                    example: kj67:3818jh
                  status:
                    type: number
                    example: 1

        '404':
          description: Not found
        '500':
          description: Internal error

  /devices/{device_id}/status:
    put:
      tags:
        - Device Control Service
      summary: Управление состоянием устройства
      parameters:
        - name: device_id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                    example: 1
                  device_type_id:
                    type: integer
                    example: 1
                  house_id:
                    type: number
                    example: 3
                  serial:
                    type: string
                    example: kj67:3818jh
                  status:
                    type: number
                    example: 0

        '404':
          description: Not found
        '500':
          description: Internal error

  /devices/{device_id}/commands:
    post:
      tags:
        - Device Control Service
      summary: Отправляет команду устройству
      parameters:
        - name: device_id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                command:
                  type: string
                  example: temperature
                value:
                  type: string
                  example: "22"
      responses:
        '200':
          description: Success
        '404':
          description: Not found
        '500':
          description: Internal error

  /monitoring/{device_id}/latest:
    get:
      tags:
        - Monitoring Service
      summary: Возвращает актуальное значение телеметрии устройства
      parameters:
        - name: device_id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                    example: 1
                  device_id:
                    type: number
                    example: 34
                  data:
                    type: object
                    example: {
                      "type": "temperature",
                      "value": "20",
                      "scale": "C",
                    }
                  for_date:
                    type: string
                    example: '2024-10-10 19:20:00'
        '404':
          description: Not found
        '500':
          description: Internal error

  /monitoring/{device_id}/telemetry:
    get:
      tags:
        - Monitoring Service
      summary: Возвращает исторические данные телеметрии устройства
      parameters:
        - name: device_id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                      example: 1
                    device_id:
                      type: number
                      example: 34
                    prop:
                      type: string
                      example: temperature
                    value:
                      type: string
                      example: 22.5
                    for_date:
                      type: string
                      example: '2024-10-10 19:20:00'
        '404':
          description: Not found
        '500':
          description: Internal error

  /schedule/{device_id}/:
    post:
      tags:
        - Schedule Service
      summary: Создаёт сценарий работы устройства
      parameters:
        - name: device_id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                starts:
                  type: string
                  example: '2024-12-12 00:00:00'
                ends:
                  type: string
                  example: '2025-01-12 00:00:00'
                weekdays:
                  type: boolean
                  example: false
                weekends:
                  type: boolean
                  example: false
                data:
                  example: [
                    {
                      turnOn: '2024-12-12 04:00:00',
                      turnOff: '2024-12-13 00:00:00',
                    },
                    {

                      turnOn: '2024-12-15 04:00:00',
                      turnOff: '2024-12-16 00:00:00',
                    },
                  ]
      responses:
        '201':
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  schedule_id:
                    type: integer
                    example: 1
                  device_id:
                    type: number
                    example: 34
                  status:
                    type: string
                    example: success
        '400':
          description: Bad request. Error when creating schedule...
        '422':
          description: Unprocessable Entity
        '500':
          description: Internal error

  /schedule/{device_id}:
    delete:
      tags:
        - Schedule Service
      summary: Удаляет сценарий работы устройства
      parameters:
        - name: device_id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Success
        '500':
          description: Internal error

  /schedule/{device_id}/info:
    get:
      tags:
        - Schedule Service
      summary: Создаёт сценарий работы устройства
      parameters:
        - name: device_id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  starts:
                    type: string
                    example: '2024-12-12 00:00:00'
                  ends:
                    type: string
                    example: '2025-01-12 00:00:00'
                  weekdays:
                    type: boolean
                    example: false
                  weekends:
                    type: boolean
                    example: false
                  data:
                    example: [
                      {
                        turnOn: '2024-12-12 04:00:00',
                        turnOff: '2024-12-13 00:00:00',
                      },
                      {

                        turnOn: '2024-12-15 04:00:00',
                        turnOff: '2024-12-16 00:00:00',
                      },
                    ]
        '404':
          description: Not found
        '500':
          description: Internal error