@startuml

title SmartHome System Context Diagram

top to bottom direction

!includeurl https://raw.githubusercontent.com/butenromayandex/C4/main/C4_Component.puml

!define DEVICONS https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/master/devicons
!define FONTAWESOME https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/master/font-awesome-5
!include DEVICONS/java.puml
!include FONTAWESOME/users.puml

Person(user, "Пользователи", "Пользователи системы  SmartHome", $sprite="users")
Person(admin, "Администраторы", "Администраторы системы  SmartHome", $sprite="users")

System(SmartHomeSystem, "SmartHome System", "Управление отоплением в домах пользователей, мониторинг текущей температуры", $sprite="java")
System_Ext(sensors, "Внешние модули/устройства")

Rel(user, SmartHomeSystem, "Управление температурой")
Rel(user, SmartHomeSystem, "Просмотр текущей температуры в доме")
Rel(admin, SmartHomeSystem, "Управление пользователями")
Rel(SmartHomeSystem, sensors, "Управление датчиками")
Rel(SmartHomeSystem, sensors, "Мониторинг температуры")

@enduml